Repository wdhurleyjr/CST438-Project2-API, pull requests merged in 2024-10, with the labels that each got.

#27 Updated Dockerfile.
  Dockerfile
Labels: enhancement, backend, setup, API, design

#29 Created docker-compose
  docker-compose.yml
Labels: enhancement, backend, setup, API, design

#31 Created Makefile for Building and Deploying Docker Image to Heroku
  Makefile
Labels: enhancement, backend, setup, API

#36 Created Root Controller Test
  src/test/java/com/project2/Project2/controller/RootControllerTest.java
Labels: enhancement, backend, API, design, testing

#38 Created User Service Tests
  src/test/java/com/project2/Project2/service/UserServiceTest.java
Labels: enhancement, backend, API, design, testing

#34 Created User Controller Test
  pom.xml
  src/test/java/com/project2/Project2/controller/UserControllerTest.java
Labels: enhancement, backend, API, design, testing

#40 Feature/user model update
  src/main/java/com/project2/Project2/model/User.java
Labels: enhancement, setup, API

#41 Added wishlist CRUD operations to feature/UserService updated
  src/main/java/com/project2/Project2/service/UserService.java
Labels: enhancement, setup, API

#42 Added wishlist endpoints to feature/UserController update
  src/main/java/com/project2/Project2/controller/UserController.java
Labels: enhancement, setup, API

#43 Fix: Implemented Search Functionality for BookController and BookService
  docker-compose.yml
  pom.xml
  src/main/java/com/project2/Project2/controller/BookController.java
  src/main/java/com/project2/Project2/controller/UserController.java
  src/main/java/com/project2/Project2/model/Book.java
  src/main/java/com/project2/Project2/repository/BookRepository.java
  src/main/java/com/project2/Project2/service/BookService.java
  src/main/resources/application.properties
Labels: backend, API, Search

#45 Add `Set<String>` for Roles in `User` Model to Support Role-Based Access Control
  src/main/java/com/project2/Project2/controller/RootController.java
  src/main/java/com/project2/Project2/model/User.java
Labels: enhancement, backend, setup, API, design

#47 Fix Makefile and Docker-Compose to Support Dynamic Image Selection
  Makefile
  docker-compose.yml
Labels: enhancement, backend, API

#49 Update `UserService` and `UserController` to Add Support for User Roles
  src/main/java/com/project2/Project2/controller/UserController.java
  src/main/java/com/project2/Project2/service/UserService.java
Labels: enhancement, setup, API, design

#51 Update `UserService` and `UserController` to Add Support for User Roles
  pom.xml
  src/main/java/com/project2/Project2/controller/UserController.java
  src/main/java/com/project2/Project2/security/SecurityConfig.java
  src/main/java/com/project2/Project2/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement, backend, setup, API, design

#52 Implemented book search and populateBooks tests
  src/main/java/com/project2/Project2/model/Book.java
  src/main/java/com/project2/Project2/service/BookService.java
  src/test/java/com/project2/Project2/service/BookServiceTest.java
Labels: backend, API, Database, testing

#53 Implement Amazon URL Generation and Add Unit Tests
  src/main/java/com/project2/Project2/controller/BookController.java
  src/main/java/com/project2/Project2/service/BookService.java
  src/test/java/com/project2/Project2/service/BookServiceTest.java
Labels: backend, testing, AWS, endpoint

#54 Added Image URL Update Feature for Books
  src/main/java/com/project2/Project2/controller/BookController.java
  src/main/java/com/project2/Project2/service/BookService.java
  src/test/java/com/project2/Project2/service/BookServiceTest.java
Labels: backend, API, Database

#55 Enhanced Book Data Model and Updated Test Cases
  src/main/java/com/project2/Project2/controller/BookController.java
  src/main/java/com/project2/Project2/model/Book.java
  src/main/java/com/project2/Project2/repository/BookRepository.java
  src/main/java/com/project2/Project2/service/BookService.java
  src/test/java/com/project2/Project2/service/BookServiceTest.java
Labels: backend, API, testing

#56 Add `AuthController` and JWT-Based Authentication
  docker-compose.yml
  pom.xml
  src/main/java/com/project2/Project2/Project2Application.java
  src/main/java/com/project2/Project2/controller/AuthController.java
  src/main/java/com/project2/Project2/controller/UserController.java
  src/main/java/com/project2/Project2/model/AuthRequest.java
  src/main/java/com/project2/Project2/model/AuthResponse.java
  src/main/java/com/project2/Project2/model/User.java
  src/main/java/com/project2/Project2/security/JwtRequestFilter.java
  src/main/java/com/project2/Project2/security/SecurityConfig.java
  src/main/java/com/project2/Project2/service/JwtService.java
  src/main/java/com/project2/Project2/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement, backend, setup, API, Database, design, data-population

#58 Fix Test Cases and Enhance User Model Functionality
  src/main/java/com/project2/Project2/model/User.java
  src/test/java/com/project2/Project2/controller/RootControllerTest.java
  src/test/java/com/project2/Project2/controller/UserControllerTest.java
  src/test/java/com/project2/Project2/service/UserServiceTest.java
Labels: backend, testing

#62 Refactor `AuthController`, `JwtService`, and `User` Model for Enhanced Role Management
  src/main/java/com/project2/Project2/controller/AuthController.java
  src/main/java/com/project2/Project2/model/User.java
  src/main/java/com/project2/Project2/service/JwtService.java
Labels: backend, API, design

#64 Feature/auth controller test
  src/test/java/com/project2/Project2/controller/AdminControllerTest.java
  src/test/java/com/project2/Project2/controller/AuthControllerTest.java
  src/test/java/com/project2/Project2/controller/BookControllerTest.java
  src/test/java/com/project2/Project2/controller/UserControllerTest.java
  src/test/java/com/project2/Project2/security/JwtRequestFilterTest.java
  src/test/java/com/project2/Project2/security/SecurityConfigTest.java
  src/test/java/com/project2/Project2/service/JwtServiceTest.java
  src/test/java/com/project2/Project2/service/UserServiceTest.java
Labels: backend, API, design, testing

#65 Create test for AdminController.
  src/test/java/com/project2/Project2/controller/AdminControllerTest.java
Labels: backend, API, testing

#66 Created JwtServiceTest
  src/main/java/com/project2/Project2/service/JwtService.java
  src/test/java/com/project2/Project2/service/JwtServiceTest.java
Labels: backend, API, design, testing

#67 Created tests for JwtRequestFilter
  src/test/java/com/project2/Project2/security/JwtRequestFilterTest.java
Labels: backend, API, testing
